services:
  - type: web
    name: novarix-studio
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: novarix-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: novarix-db
    databaseName: novarix_studio
    user: novarix_user
    plan: starter